#template GitLab CI pour Node.js  
image: node:18

stages:
  - install
  - lint
  - unit test 
  - integration test

install:
  stage: install
  script:
    - npm install

lint:
  stage: lint
  script:
    - npm run lint




