# workflow GitHub Actions pour Python
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Lint with flake8
        run: flake8 .


# Les jobs de déploiement seront ajoutés ici


  unit_tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - run: pytest tests/unit
  integration_tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - run: pytest tests/integration

  deploy_dev:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Déploiement Python vers dev...' && ./scripts/deploy.sh dev

  deploy_staging:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Déploiement Python vers staging...' && ./scripts/deploy.sh staging

  deploy_prod:
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Déploiement Python vers prod...' && ./scripts/deploy.sh prod

