#template GitLab CI pour Node.js  
image: node:18

stages:
  - install
  - lint
  - test
  - integration
  - deploy

install:
  stage: install
  script:
    - npm install

lint:
  stage: lint
  script:
    - npm run lint

# Les jobs de test et de déploiement seront ajoutés ici par le générateur